name = "TerraFirmaGreg-Modern"
author = "Exception, Xikaro, Ant1och"
version = "0.9.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "304c8989faadff4092838bc0116068ce037dd39a2736a66d0954a113bc31b5df"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
