name = "TerraFirmaGreg-Modern"
author = "Exception, Xikaro, Ant1och"
version = "0.9.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad496375502ed0564933258bef4f3cf3c22eb01553858ff86f335751987bf7cb"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
