name = "TerraFirmaGreg-Modern"
author = "Exception, Xikaro"
version = "0.9.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51119324ea123421fb1c0939843fa8dd891d921b767317a34029c1ea5aaaf940"

[versions]
forge = "47.2.6"
minecraft = "1.20.1"
